# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  push:
    branches: [ master, dev, unit-tests-integration ]
  pull_request:
    branches: [ master, dev, unit-tests-integration ]

jobs:
  api_tests:
    name: "Run API Tests"
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm --prefix ./server ci
    - run: npm --prefix ./server test
      env:
        CI: true
